version = 3.10.4
runner.dialect = Scala33
fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}
project.excludePaths = ["glob:**/examples/**", "glob:**/.bloop/**", "glob:**/.bsp/**", "glob:**/.metals/**"]
align.preset = some
maxColumn = 75

